name: Build Kernel A12 with LXC and Kali NetHunter

on:
  push:
    branches:
      - main
      - ci
      - checkci
  pull_request:
    branches:
      - main

jobs:
  build-kernel:
    strategy:
      matrix:
        sub_level:
          - 'aosp-mainline'
        os_patch_level:
          - '2023-05'
          - '2023-06'
          - '2023-07'
    uses: ./.github/workflows/gki-kernel-lxc.yml
    secrets:
      KERNELSU_TOKEN: ${{ secrets.KERNELSU_TOKEN }}
    with:
      version: aosp-mainline
      version_name: aosp-mainline
      tag: ${GITHUB_REF_NAME}-${{ matrix.os_patch_level }}-${{ matrix.sub_level }}
      patch_path: patches/aosp-mainline/${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      arch: arm64
      kernel_config: vendor/oneplus/sm8250-perf_defconfig
      add_kprobes_config: true
      add_overlayfs_config: true
      disable_lto: false
      disable_cc_werror: false
      disable_fst: false
      enable_lxc: true
      enable_nethunter: true

  upload-artifacts:
    needs: build-kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts from previous job
        uses: actions/download-artifact@v4
        with:
          name: kernel-images

      - name: Upload artifacts to GitHub Releases
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          files: |
            *.gz
          body: Release of kernel images for A12 with LXC and Kali NetHunter support.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
